[server]
SERVICE_NAME = "service"
VERSION = "0.0.1"
PORT = 8080

[database]
TYPE="SQLITE"
HOST=""
PORT=""
SSLMODE=""
DATABASE=""
SCHEMA=""
USERNAME=""
PASSWORD=""
TIMEZONE=""

[nsq]
DAEMON_URL="localhost:4150"
LOOKUP_DAEMON_URL="localhost:4161"
